version: '3.8'

services:

  frontend:
    image: ml-frontend
    build:
      context: ./ml-kurkkumopo-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    image: ml-backend
    build:
      context: ./ml-kurkkumopo-backend
      dockerfile: Dockerfile
    volumes:
      - model:/src/model
    ports:
      - 5000:5000
    depends_on:
      - training

  training:
    image: ml-training
    build:
      context: ./ml-kurkkumopo-training
      dockerfile: Dockerfile
    volumes:
      - model:/src/model
      - imgs:/src/imgs

volumes:
  model: null
  imgs: null
